# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AmazonLoginDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AmazonLoginDemo

  target 'AmazonLoginDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AmazonLoginDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

    pod 'AWSUserPoolsSignIn', '~> 2.6.6'
    pod 'AWSAuthUI', '~> 2.6.6'
    pod 'AWSMobileClient', '~> 2.6.6'
    pod 'FacebookLogin'
    pod 'AWSFacebookSignIn', '~> 2.6.6'
    pod 'GoogleSignIn'
    pod 'Google/SignIn'
    pod 'AWSGoogleSignIn', '~> 2.6.6'
    pod 'GoogleSignIn', '~> 4.0'
end
